config/routes.rb
Legomni::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :devices

  resources :user_figures

  resources :figures

  resources :series do
    resources :figures
  end

  match "users/:user_id/series/:series_index/figures/:figure_index" => redirect("/user_figures/show/%{user_id}/%{series_index}/%{figure_index}")
  match "users/:user_id/figures/:figure_code" => redirect("/user_figures/show/%{user_id}/%{figure_code}")
  devise_for :users, :path_prefix => 'd'
  resources :users do
    resources :user_figures
    resources :devices

  end

  match ":controller/:action/:user_id/:figure_code"
  match ":controller/:action/:user_id/:series_index/:figure_index"

  root :to => 'home#index'

end

app/models/user_figure.rb
class UserFigure < ActiveRecord::Base
  attr_accessible :count, :first_at, :wanted, :give, :user_id, :figure_code
  belongs_to :user
  belongs_to :figure

end

app/controllers/user_figures_controller.rb
class UserFiguresController < ApplicationController

  def user_figure_by_code_or_id(params)
    id = params[:id]
    figure_code = params[:figure_code]
    return UserFigure.find(params[:id]) if id
    return UserFigure.find_by_figure_code( params[:figure_code] ) if figure_code
    return UserFigure.find_by_figure_code( "#{params[:series_index]}-#{params[:figure_index]}" )
  end

  # GET /user_figures
  # GET /user_figures.json
  def index
    @user_figures = UserFigure.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_figures }
    end
  end

  # GET /user_figures/1
  # GET /user_figures/1.json
  def show
    @user_figure = self.user_figure_by_code_or_id(params)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_figure }
    end
  end

  # GET /user_figures/new
  # GET /user_figures/new.json
  def new
    @user_figure = UserFigure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_figure }
    end
  end

  # GET /user_figures/1/edit
  def edit
    @user_figure = self.user_figure_by_code_or_id(params)
  end

  # POST /user_figures
  # POST /user_figures.json
  def create
    @user_figure = UserFigure.new(params[:user_figure])

    respond_to do |format|
      if @user_figure.save
        format.html { redirect_to @user_figure, notice: 'User figure was successfully created.' }
        format.json { render json: @user_figure, status: :created, location: @user_figure }
      else
        format.html { render action: "new" }
        format.json { render json: @user_figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_figures/1
  # PUT /user_figures/1.json
  def update
    @user_figure = UserFigure.find(params[:id])

    respond_to do |format|
      if @user_figure.update_attributes(params[:user_figure])
        format.html { redirect_to @user_figure, notice: 'User figure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_figures/1
  # DELETE /user_figures/1.json
  def destroy
    @user_figure = UserFigure.find(params[:id])
    @user_figure.destroy

    respond_to do |format|
      format.html { redirect_to user_figures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_figures_helper.rb
module UserFiguresHelper
end

app/views/user_figures/_form.html.erb
<%= form_for(@user_figure) do |f| %>
  <% if @user_figure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_figure.errors.count, "error") %> prohibited this user_figure from being saved:</h2>

      <ul>
      <% @user_figure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :figure_code %><br />
    <%= f.text_field :figure_code %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
    <div class="field">
      <%= f.label :wanted %><br />
      <%= f.number_field :wanted %>
    </div>
    <div class="field">
      <%= f.label :give %><br />
      <%= f.number_field :give %>
    </div>
    <div class="field">
    <%= f.label :first_at %><br />
    <%= f.date_select :first_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_figures/edit.html.erb
<h1>Editing user_figure</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_figure %> |
<%= link_to 'Back', user_figures_path %>

app/views/user_figures/index.html.erb
<h1>Listing user_figures</h1>

<table>
  <tr>
    <th>User</th>
    <th>Figure</th>
    <th>Count</th>
    <th>Wanted?</th>
    <th>Give?</th>
    <th>First at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_figures.each do |user_figure| %>
  <tr>
    <td><%= user_figure.user_id %></td>
    <td><%= user_figure.figure_code %></td>
    <td><%= user_figure.count %></td>
    <td><%= user_figure.wanted %></td>
    <td><%= user_figure.give %></td>
    <td><%= user_figure.first_at %></td>
    <td><%= link_to 'Show', user_figure %></td>
    <td><%= link_to 'Edit', edit_user_figure_path(user_figure) %></td>
    <td><%= link_to 'Destroy', user_figure, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User figure', new_user_figure_path %>

app/views/user_figures/new.html.erb
<h1>New user_figure</h1>

<%= render 'form' %>

<%= link_to 'Back', user_figures_path %>

app/views/user_figures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_figure.user_id %>
</p>

<p>
  <b>Figure:</b>
  <%= @user_figure.figure_code %>
</p>

<p>
  <b>Count:</b>
  <%= @user_figure.count %>
</p>

<p>
  <b>Wanted?:</b>
  <%= @user_figure.wanted %>
</p>

<p>
  <b>Give?:</b>
  <%= @user_figure.give %>
</p>

<p>
  <b>First at:</b>
  <%= @user_figure.first_at %>
</p>


<%= link_to 'Edit', edit_user_figure_path(@user_figure) %> |
<%= link_to 'Back', user_figures_path %>