config/routes.rb
Legomni::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :devices

  resources :user_figures

  resources :figures

  resources :series do
    resources :figures
  end

  match "users/:user_id/series/:series_index/figures/:figure_index" => redirect("/user_figures/show/%{user_id}/%{series_index}/%{figure_index}")
  match "users/:user_id/figures/:figure_code" => redirect("/user_figures/show/%{user_id}/%{figure_code}")
  devise_for :users, :path_prefix => 'd'
  resources :users do
    resources :user_figures
    resources :devices

  end

  match ":controller/:action/:user_id/:figure_code"
  match ":controller/:action/:user_id/:series_index/:figure_index"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /devices
  # GET /devices.json
  def index
    #@devices = Device.all
    #
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @devices }
    #end
  end

end

app/views/home/index.html.erb
<script type="text/javascript">
    function about() {
        info = document.getElementById('about-content');
        if (window.XMLHttpRequest)
        { xhr = new XMLHttpRequest(); }
        else
        { xhr = new ActiveXObject("Microsoft.XMLHTTP"); }
        xhr.open("GET","rails/info/properties",false);
        xhr.send("");
        info.innerHTML = xhr.responseText;
        info.style.display = 'block'
    }
</script>

<div id="page">
  <div id="sidebar">
    <ul id="sidebar-items">
      <li>
        <h3>
          <% if user_signed_in? %>
                <% if !current_user.firstName.empty? || !current_user.lastName.empty? %>
                    <%= "#{current_user.firstName} #{current_user.lastName}" %>
                <% else %>
                    <%= "#{current_user.email}" %>
                <% end%>
          <% else %>
          Connection
          <% end %>
        </h3>
        <ul class="links">
          <% if user_signed_in? %>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% else %>
              <li><%= link_to('Login', new_user_session_path)  %></li>
              <li><%= link_to 'Sign Up', '/users/sign_up' %></li>
          <% end %>

        </ul>

        <h3>Actions</h3>
        <ul class="links">
          <li><%= link_to 'Figures', figures_path %></li>
          <li><%= link_to 'Series', series_index_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Devices', devices_path %></li>
          <li><%= link_to 'UserFigures', user_figures_path %></li>

        </ul>
      </li>
    </ul>
  </div>

  <div id="content">
    <div id="header">
      <h1>Legomni</h1>
      <h2>Echanger vos LEGO miniFigures</h2>
    </div>

    <div id="about">
      <h3><a href="rails/info/properties" onclick="about(); return false">About your application&rsquo;s environment</a></h3>
      <div id="about-content" style="display: none"></div>
    </div>

    <div id="getting-started">
      <h1>Getting started</h1>
      <h2>Here&rsquo;s how to get rolling:</h2>

      <ol>
        <li>
          <h2>Créer un compte</h2>
          <p>Afin de pouvoir enregistrer, gérer et échanger vos LEGO miniFigures.</p>
        </li>

        <li>
          <h2>L'application iPhone / iPad</h2>
          <p>Pour toujours avoir sur vous vos LEGO miniFigures.</p>
        </li>

      </ol>
    </div>
  </div>

  <div id="footer">&nbsp;</div>
</div>