config/routes.rb
Legomni::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :devices

  resources :user_figures

  resources :figures

  resources :series do
    resources :figures
  end

  match "users/:user_id/series/:series_index/figures/:figure_index" => redirect("/user_figures/show/%{user_id}/%{series_index}/%{figure_index}")
  match "users/:user_id/figures/:figure_code" => redirect("/user_figures/show/%{user_id}/%{figure_code}")
  devise_for :users, :path_prefix => 'd'
  resources :users do
    resources :user_figures
    resources :devices

  end

  match ":controller/:action/:user_id/:figure_code"
  match ":controller/:action/:user_id/:series_index/:figure_index"

  root :to => 'home#index'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  # GET /series
  # GET /series.json
  def index
    @series = Series.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @series = Series.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/new
  # GET /series/new.json
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1/edit
  def edit
    @series = Series.find(params[:id])
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(params[:series])

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render json: @series, status: :created, location: @series }
      else
        format.html { render action: "new" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /series/1
  # PUT /series/1.json
  def update
    @series = Series.find(params[:id])

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br />
    <%= f.number_field :index %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Index</th>
    <th>Color</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @series.each do |series| %>
  <tr>
    <td><%= series.series_code %></td>
    <td><%= series.index %></td>
    <td><%= series.color %></td>
    <td><%= series.url %></td>
    <td><%= link_to 'Show', series %></td>
    <td><%= link_to 'Edit', edit_series_path(series) %></td>
    <td><%= link_to 'Destroy', series, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Index:</b>
  <%= @series.index %>
</p>

<p>
  <b>Color:</b>
  <%= @series.color %>
</p>

<p>
  <b>Url:</b>
  <%= @series.url %>
</p>


<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>